name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code source du dépôt
    - uses: actions/checkout@v4

    # 2. Configurer le JDK (indispensable pour Maven)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # 3. Exécuter les tests (votre demande initiale)
    - name: Run tests
      run: mvn clean test

    # 4. Créer le package (JAR)
    - name: Build with Maven
      run: mvn package -DskipTests # On skip les tests car ils viennent d'être faits au step précédent

    # 5. Sauvegarder le dossier target/ comme artefact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bank-application-build-folder
        path: target/
        retention-days: 5
